### ISSUE TITLE
Update the details for MUSES and TadTR

### ISSUE THREAD

**Issue by xlliu7** [zhenyingfang/Awesome-Temporal-Action-Detection-Temporal-Action-Proposal-Generation#3]
Hi, could you update the details for MUSES and TadTR?

(TadTR) [End-to-end Temporal Action Detection with Transformer](https://arxiv.org/abs/2106.10271) (TIP 2022) [code](https://github.com/xlliu7/TadTR)
(MUSES) [Multi-shot Temporal Event Localization: a Benchmark](https://arxiv.org/abs/2012.09434) (CVPR 2021) [project](https://songbai.site/muses/) [code](https://github.com/xlliu7/MUSES) [dataset](https://songbai.site/muses/)

Thanks.

**Comment by zhenyingfang** [comment]
> Hi, could you update the details for MUSES and TadTR?
> 
> (TadTR) [End-to-end Temporal Action Detection with Transformer](https://arxiv.org/abs/2106.10271) (TIP 2022) [code](https://github.com/xlliu7/TadTR) (MUSES) [Multi-shot Temporal Event Localization: a Benchmark](https://arxiv.org/abs/2012.09434) (CVPR 2021) [project](https://songbai.site/muses/) [code](https://github.com/xlliu7/MUSES) [dataset](https://songbai.site/muses/)
> 
> Thanks.

Updated, Great Work.
